FROM mcr.microsoft.com/devcontainers/python:1-3.9

RUN apt-get update && apt-get install -y libx11-xcb1 libxcomposite1 libxcursor1 libxss1 libgbm1 \
                                         libatk-bridge2.0-0 libgtk-3-0 libxrandr2 libasound2 \
                                         libxdamage1 libxi6 libxtst6 libnss3 libcups2 libatk1.0-0
