name: testing

on: [push, pull_request]

jobs:
    pytest:
        permissions:
            contents: read
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Install Python 3.9
          uses: actions/setup-python@v5
          with: 
            python-version: "3.9"
        - name: Install dependencies
          run: |
            python -m venv venv
            source venv/bin/activate
            pip install ".[test]"
        - name: Run Pytest
          run: |
            source venv/bin/activate
            mv comparison_interface/static/example.images/ comparison_interface/static/images/
            mv  comparison_interface/configuration/example.flask.py comparison_interface/configuration/flask.py
            pytest -v tests_python

    javascript_tests:
        permissions:
            contents: read
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - name: Install Node
          uses: actions/setup-node@v4
          with:
            node-version: '22'
        - name: Install dependencies
          run: npm i  jest@^29.7.0 jest-environment-jsdom@^29.7.0
        - name: Run tests
          run: npx jest -- tests_javascript
